### ISSUE TITLE
Construct Projector for Hyper-reduced Galerkin ROM

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio-distributed-linalg#9]
**Inputs:**

Required:
```
input: full path to yaml input file.
data-dir: full path to where data lives.
state-file-root-name: [string] file name root for the state basis. Assumes decomposed files with the names <residual-basis-root-name>.XX.YY, where XX is the total number of files and YY is the rank number for a given file. Note that the total number of files must be = to MPI size
state-format: [string] binary or ascii: format of the state basis file(s)
state-num-columns:  [int] number of columns in the state basis
num-mesh-nodes: [int] number of nodes in the mesh
sample-mesh-indices: [string] filename for ascii file containing sample mesh global indices
hyper-reduction-type: [string] "gappy-pod" or "collocation", type of hyper-reduction being performed. 
out-format: [string] binary or ascii: format in which the projector matrix is written to disk
```
Optional:
```
res-file-root-name: [string] file name root for the residual basis.
res-format: [string] binary or ascii: format of the residual basis file(s)
res-num-columns:  [int] number of columns in the residual basis
out-dir: full path to directory to store results, i.e. file with node lists, etc. If nothing is passed, we use as output the directory where data is loaded from.
```

To run:
```
mpirun -np num-procs python construct_galerkin_projector.py --input yaml-file-name [--data-dir full-path-to-data --out-dir full-path-to-output-files]
```

Requirements:
-All input integers should be non-zero and positive.
-binary files have double-precision numbers (could add support for 32-bit later...)
-# of entries read in from state or residual basis files should be [state/res]-num-columns * num-mesh-nodes * dofs-per-mesh-node
-num-sample-mesh-nodes < num-mesh-nodes

**Outputs**: 
Binary (or ascii) file(s) with projector matrix (# of sample mesh unknowns by # of generalized coordinates)

**Comment by pjb236** [comment]
```py

input_dict = parse_yaml_input(input_filename)

# Read state basis
state_basis = read_matrix(input_dict["StateBasis"])

# Read residual basis if required or specified
hyp_type = input_dict["ProjectorMatrix"]["kind"]
if (hyp_type == "gappy_pod") or  input_dict["ResBasis"]:
  res_basis = read_matrix(input_dict["ResBasis"])
else:
  res_basis = state_basis

# Read sample mesh indices
sample_mesh_inds = read_sample_mesh_inds(input_dict["SampleMesh"])

# construct sampling matrix
sampling_mat = construct_sampling_matrix(sample_mesh_inds)

# check hyper-reduction type
if hyp_type == "collocation":
  projector = state_basis.transpose() * sampling_mat.transpose()
elif hyp_type =="gappy_pod":
  projector = state_basis.transpose() * res_basis *  pseudo_inverse(sampling_mat * res_basis)

# output projector
write_matrix_to_file(input_dict, projector)

```

**Comment by pjb236** [comment]
@fnrizzi, let's start with this one since the LSPG counterpart (#10) just requires a few extra operations.

**Comment by fnrizzi** [comment]
* is the residual basis mandatory or optional for gappy-pod?

**Comment by fnrizzi** [comment]
When we do the computation, we cannot use `.transpose()` because it won't work for the the distributed matrices. 
We can just use BLAS-like api that we specialize behind the scenes so that it will work for both distributed and on-node

```py
# check hyper-reduction type
hyp_type = input_dict["hyper-reduction-type"]
if hyp_type == "collocation":
  # projector = state_basis.transpose() * sampling_mat.transpose()
  pressiotools.lingalg.product(transpose, transpose, 1., state_basis, sampling_mat, 0, projector)
elif hyp_type =="gappy_pod":
  # projector = state_basis.transpose() * res_basis *  pseudo_inverse(sampling_mat * res_basis)
  B = sampling_mat * res_basis
  B1 = pressiotools.lingalg.pseudo_inverse(B)
  pressiotools.lingalg.product(transpose, nontranspose, 1., state_basis, B1, 0, projector)
```

**Comment by fnrizzi** [comment]
My draft of the input based on what you suggested: 

```yaml
# **mandatory**
# needed by both state and residual basis
FullMeshInfo: 
  # [int] number of nodes in the mesh
  num-mesh-nodes: 9

  # [int] number of degrees of freedom at each mesh node
  dofs-per-mesh-node: 2


# **mandatory**
StateBasis: 
  # file name root for the matrix file(s).
  # If doing parallel run: 
  #     assume files decomposed as <file-root-name>.XX.YY,
  #     where XX is the total number of files and YY is the rank number for a given file.
  #     Note that the total number of files must be = to MPI size
  # If doing onnode: 
  #     assume single file named <file-root-name>.1.0
  file-root-name: "some string"

  # format of the file(s)
  format: "binary" or "ascii"

  # [int] number of columns/basis
  num-columns: 10


# **optional**
ResidualBasis: 
  # file name root for the matrix file(s).
  # If doing parallel run: 
  #     assume files decomposed as <file-root-name>.XX.YY,
  #     where XX is the total number of files and YY is the rank number for a given file.
  #     Note that the total number of files must be = to MPI size
  # If doing onnode: 
  #     assume single file named <file-root-name>.1.0
  file-root-name: "some string"

  # [string] binary or ascii: format of the file(s)
  format: "binary"

  # [int] number of columns/basis
  num-columns: 10


# **mandatory**
ProjectorMatrix: 
  # type of hyper-reduction being performed. 
  # if collocation, ResidualBasis is optional
  # if gappy-pod,   ResidualBasis is mandatory
  kind: "collocation" or "gappy-pod" 

  # file containing the sample mesh nodes indices. 
  # this is the file generated, using, e.g., one of the sample mesh driver scripts.
  sample-mesh-indices-filename: "something" 

  # format to write
  format: "binary" or "ascii"
```
